### ISSUE TITLE
Full code not shown

### ISSUE THREAD

**Issue by amitness** [shadowfacts/type#2]
I tried the tool for two repos. In both of them, the full code is not displayed for practice.

Here's an example:

Original code: [here](https://github.com/sdispater/pendulum/blob/master/setup.py)
On the practise page: [here](https://type.shadowfacts.net/type.html#sdispater/pendulum/master/setup.py)

**Comment by amitness** [comment]
I figured it out. You need to hit enter after the last code. Please add it in the usage section, maybe.

**Comment by shadowfacts** [comment]
Yep, each file is split up into 50 line chunks for performance reasons.
